### PR TITLE
FIX spelling loal -> local

### PR DESCRIPTION
**Pull request by shdkej**
Hi!
I've looked around your blog and exciting these all content.
I'm your fan.
I wonder how you make a todo list and managing this.
Can you share how to manage your todo list?
Thanks.

### CODE REVIEW

**Review by johngrib — APPROVED** [review]
Thank you. I will write about to-do management.

**Comment by johngrib** [comment]
There is an article I wrote earlier.
https://johngrib.github.io/wiki/vim-update-book-progress/

**Comment by shdkej** [comment]
Oh, thanks
I've read that.
I've searched book.md and todo.md
but that's in local only, right?
Are you manage a to-do list only using vimwiki?
how to use mobile to manage to-do list?
that's just my little curious
you don't have to answer right now.
I could read your article someday,

thanks!

**Comment by johngrib** [comment]
Yes. Those files contain my personal information.
So I don't publish those files on the internet.
And I don't read those files on mobile.

**Pull request merged**
